"use strict";

const STATES = Object.freeze([
  "DETECTED","RECALLING_PATTERNS","PROPOSING_PATCH","POLICY_CHECKING",
  "SANDBOX_PENDING","SANDBOX_RUNNING","SANDBOX_VERIFIED",
  "SANDBOX_CANCELLED","CRITIC_EVALUATION","PROOF_GENERATION",
  "HUMAN_APPROVAL_REQUIRED","PR_CREATING","CI_PENDING",
  "RESOLVED","REJECTED","FAILED_RECOVERY","AUTONOMY_KILLED"
]);
const TERMINAL = new Set(["RESOLVED","REJECTED","FAILED_RECOVERY","AUTONOMY_KILLED"]);
const TRANSITIONS = Object.freeze({
  DETECTED:["RECALLING_PATTERNS","PROPOSING_PATCH","FAILED_RECOVERY","AUTONOMY_KILLED"],
  RECALLING_PATTERNS:["PROPOSING_PATCH","FAILED_RECOVERY","AUTONOMY_KILLED"],
  PROPOSING_PATCH:["POLICY_CHECKING","REJECTED","FAILED_RECOVERY","AUTONOMY_KILLED"],
  POLICY_CHECKING:["SANDBOX_PENDING","HUMAN_APPROVAL_REQUIRED","REJECTED","AUTONOMY_KILLED"],
  SANDBOX_PENDING:["SANDBOX_RUNNING","HUMAN_APPROVAL_REQUIRED","AUTONOMY_KILLED"],
  SANDBOX_RUNNING:["SANDBOX_VERIFIED","SANDBOX_CANCELLED","FAILED_RECOVERY","AUTONOMY_KILLED"],
  SANDBOX_VERIFIED:["CRITIC_EVALUATION","FAILED_RECOVERY","AUTONOMY_KILLED"],
  SANDBOX_CANCELLED:["AUTONOMY_KILLED","HUMAN_APPROVAL_REQUIRED"],
  CRITIC_EVALUATION:["PROOF_GENERATION","REJECTED","HUMAN_APPROVAL_REQUIRED","AUTONOMY_KILLED"],
  PROOF_GENERATION:["HUMAN_APPROVAL_REQUIRED","PR_CREATING","REJECTED","AUTONOMY_KILLED"],
  HUMAN_APPROVAL_REQUIRED:["PR_CREATING","REJECTED","AUTONOMY_KILLED"],
  PR_CREATING:["CI_PENDING","FAILED_RECOVERY","AUTONOMY_KILLED"],
  CI_PENDING:["RESOLVED","FAILED_RECOVERY","REJECTED","AUTONOMY_KILLED"],
  RESOLVED:[], REJECTED:[], FAILED_RECOVERY:[], AUTONOMY_KILLED:[]
});
function canTransition(from,to){ return Boolean(TRANSITIONS[from]?.includes(to)); }
function assertTransition(from,to){
  if(!STATES.includes(from)||!STATES.includes(to)) throw new Error("UNKNOWN_FSM_STATE");
  if(!canTransition(from,to)) throw new Error("INVALID_FSM_TRANSITION:"+from+"->"+to);
}
function isTerminal(state){ return TERMINAL.has(state); }
module.exports={STATES,TRANSITIONS,TERMINAL,canTransition,assertTransition,isTerminal};
