"use strict";

const { calibrateProbability } = require("./probability-calibrator");
const MODEL_VERSION = "x26-v1-calibrated";
const ACTION_COSTS = Object.freeze({ RESPOND:250, FOLLOW_UP:300, REACTIVATE:350, HUMAN_ESCALATION:900, WAIT:25, DO_NOT_CONTACT:0 });
function clamp(value,min=0,max=1){return Math.max(min,Math.min(max,Number(value)||0));}
function clampInt(value,min,max){return Math.round(Math.max(min,Math.min(max,Number(value)||0)));}
function ageDays(occurredAt,now=new Date()){const ts=Date.parse(String(occurredAt||""));if(!Number.isFinite(ts))return null;return Math.max(0,(now.getTime()-ts)/86400000);}
function recencyFactor(days){if(days==null)return .45;if(days<=3)return 1;if(days<=7)return .92;if(days<=14)return .82;if(days<=30)return .68;if(days<=60)return .5;if(days<=120)return .3;return .12;}
function intentFactor(intent,score){if(Number.isFinite(Number(score)))return clamp(Number(score)/100);const key=String(intent||"").toLowerCase();return key==="hot"?.9:key==="warm"?.6:key==="cold"?.25:.35;}
function valueFactor(dealValue,referenceValue=1000000){const v=Math.max(0,Number(dealValue)||0),ref=Math.max(1,Number(referenceValue)||1000000);if(v===0)return 0;return clamp(Math.log10(1+v)/Math.log10(1+ref));}
function reasonFactor(reason){const key=String(reason||"unknown").toLowerCase();if(["price","timing","no_followup","scope"].includes(key))return .9;if(["competitor","trust"].includes(key))return .68;return .5;}
function buildBaseSignals(input,now){const days=ageDays(input.occurredAt||input.lastContactAt||input.updatedAt,now);return {daysSinceEvent:days,daysSinceLastContact:ageDays(input.lastContactAt,now),recency:recencyFactor(days),intent:intentFactor(input.intent,input.leadScore),value:valueFactor(input.dealValue,input.referenceDealValue),engagement:clamp(input.engagementScore!=null?Number(input.engagementScore)/100:Math.min(1,Math.max(0,Number(input.replyCount||0)/5))),reason:reasonFactor(input.lossReason),trigger:clamp(input.triggerRelevance),contactAllowed:input.contactAllowed!==false,previousReply:Boolean(input.previousCustomerReply)};}
function recoveryScore(input,s){const score=30*s.recency+22*s.intent+18*s.value+12*s.engagement+10*s.reason+8*s.trigger;return clampInt(score-(s.contactAllowed?0:45)-((s.daysSinceEvent!=null&&s.daysSinceEvent>180)?12:0),0,100);}
function heuristicSuccessProbability(action,input,s){let p=.05+.27*s.intent+.18*s.engagement+.17*s.reason+.13*s.recency+.10*s.trigger+.10*s.value;if(action==="RESPOND"){if(input.responseSlaBreached)p+=.12;if(input.leadScore!=null&&Number(input.leadScore)>=70)p+=.08;}if(action==="FOLLOW_UP"){if(input.previousCustomerReply)p+=.10;if(s.daysSinceLastContact!=null&&s.daysSinceLastContact>=1&&s.daysSinceLastContact<=14)p+=.06;}if(action==="REACTIVATE"){p+=.10*s.trigger+.06*s.reason;}if(action==="HUMAN_ESCALATION"){if(Number(input.dealValue)>=Number(input.humanEscalationValue||1000000))p+=.10;if(input.risk==="high")p+=.08;}if(action==="WAIT")p=.06+.20*s.trigger+.10*s.recency;if(action==="DO_NOT_CONTACT")p=0;return clamp(p,.01,.95);}
function riskPenalty(action,input,s){let penalty=0;if(action!=="DO_NOT_CONTACT"&&!s.contactAllowed)penalty+=1000000000;if(action==="REACTIVATE"&&!s.trigger&&s.daysSinceEvent!=null&&s.daysSinceEvent<7)penalty+=500;if(input.marginRisk==="high"&&["REACTIVATE","FOLLOW_UP"].includes(action))penalty+=250;if(input.customerOptedOut)penalty+=1000000000;return penalty;}
function baselineProbability(s){return clamp(.03+.18*s.intent+.08*s.recency+.04*s.engagement+.05*s.trigger,.01,.50);}
function grossProfit(input){const revenue=Math.max(0,Number(input.dealValue)||0),margin=clamp(input.grossMargin!=null?Number(input.grossMargin):.30);return {revenue,margin,grossProfit:revenue*margin,marginAssumed:input.grossMargin==null};}
function candidateActions(input,s){const gp=grossProfit(input).grossProfit,history=input.historicalStats||{},costs=Object.assign({},ACTION_COSTS,input.actionCosts||{});return ["RESPOND","FOLLOW_UP","REACTIVATE","HUMAN_ESCALATION","WAIT","DO_NOT_CONTACT"].map(action=>{const heuristic=heuristicSuccessProbability(action,input,s),calibrated=calibrateProbability(heuristic,history[action]);const expectedGrossProfit=gp*calibrated.probability,cost=Math.max(0,Number(costs[action]!=null?costs[action]:0)),penalty=riskPenalty(action,input,s);return {action,probability:calibrated.probability,heuristicProbability:Number(heuristic.toFixed(4)),calibration:calibrated,expectedGrossProfit:Math.round(expectedGrossProfit),actionCost:cost,riskPenalty:penalty,expectedValue:Math.round(expectedGrossProfit-cost-penalty)};}).sort((a,b)=>b.expectedValue-a.expectedValue);}
function chooseNextAction(input,now=new Date()){const safeInput=input&&typeof input==="object"?input:{},signals=buildBaseSignals(safeInput,now),gp=grossProfit(safeInput),recovery=recoveryScore(safeInput,signals),candidates=candidateActions(safeInput,signals),best=candidates[0],suppressed=safeInput.customerOptedOut===true||signals.contactAllowed===false;return {modelVersion:MODEL_VERSION,decisionId:safeInput.decisionId||("x26-"+Date.now()+"-"+Math.random().toString(36).slice(2,8)),recoveryScore:recovery,recommendedAction:suppressed?"DO_NOT_CONTACT":best.action,expectedValue:suppressed?0:best.expectedValue,expectedIncrementalProfitKZT:suppressed?0:best.expectedValue,action:suppressed?"DO_NOT_CONTACT":best.action,baselineConversionProbability:baselineProbability(signals),dealValue:gp.revenue,grossMargin:gp.margin,marginAssumed:gp.marginAssumed,signals,candidates,explanation:{why:suppressed?"Contact is suppressed by tenant/customer policy.":"Best risk-adjusted calibrated expected value among allowed actions: "+best.action+".",assumptions:[gp.marginAssumed?"grossMargin was not supplied; 30% default is an assumption":"grossMargin supplied by caller","calibration blends heuristic probability with observed action outcomes; low sample sizes stay close to the heuristic"]}};}
function attributeRevenue(input){const recoveredRevenue=Math.max(0,Number(input?.recoveredRevenue)||0),aiCost=Math.max(0,Number(input?.aiCost)||0),humanCost=Math.max(0,Number(input?.humanCost)||0),grossMargin=clamp(input?.grossMargin!=null?Number(input.grossMargin):.30),attributedGrossProfit=recoveredRevenue*grossMargin,totalInterventionCost=aiCost+humanCost,incrementalGrossProfit=attributedGrossProfit-totalInterventionCost,roiMultiple=totalInterventionCost>0?attributedGrossProfit/totalInterventionCost:null;return {modelVersion:MODEL_VERSION,dealValue:Math.max(0,Number(input?.dealValue)||0),recoveredRevenue,grossMargin,attributedGrossProfit:Math.round(attributedGrossProfit),aiCost,humanCost,totalInterventionCost,incrementalGrossProfit:Math.round(incrementalGrossProfit),roiMultiple:roiMultiple==null?null:Number(roiMultiple.toFixed(3)),outcome:recoveredRevenue>0?"RECOVERED":"NOT_RECOVERED"};}
module.exports={MODEL_VERSION,ACTION_COSTS,chooseNextAction,attributeRevenue,recoveryScore};
