"use strict";

const { createGithubPrAdapter } = require("./github-pr-adapter");

function createLiveGithubPrAdapter({ github }) {
  if (!github) throw new TypeError("github is required");

  return createGithubPrAdapter({
    create: async ({ mission, execution }) => {
      const run = mission?.input?.workflowRun || mission?.input?.workflow_run || {};
      const base = run?.repository?.default_branch || "main";
      const head = execution?.candidate?.branch;
      if (!head) throw new Error("candidate_branch_required");

      return github.createPullRequest({
        title: execution?.candidate?.title || "x29: automated repair",
        head,
        base,
        body: [
          "Generated by bounded X29 repair runtime.",
          "",
          "Sandbox proof: PASS",
          "Kill Critic: ALLOW",
          `Source workflow run: ${run?.id || "unknown"}`
        ].join("\n")
      });
    }
  });
}

module.exports = { createLiveGithubPrAdapter };
